### ISSUE TITLE
SSL guidance

### ISSUE THREAD

**Issue by gregbty** [dtretyakov/teamcity-azure-template#4]
Is there any guidance for enabling SSL using this setup? There seems to be much more involved than just opening the firewall rule for HTTPS for the VM.

**Comment by dtretyakov** [comment]
For that could be used Azure Application Gateway service: https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-portal

Another approach is to use reverse proxy on this machine and configure SSL certificate in it. Some details could be found in the following resources:
* https://medium.com/@joatmon08/using-containers-to-learn-nginx-reverse-proxy-6be8ac75a757
* https://medium.com/@pierangelo1982/docker-nginx-and-letsencrypt-432397db4a0c
* https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/

We'll try to automate it in the next versions of this template.

**Comment by gregbty** [comment]
I assumed nginx would probably be the most likely option. Thanks!
