### ISSUE TITLE
Unable to install Microsoft Monitoring Agent(MMA) on Team city VM

### ISSUE THREAD

**Issue by anshulee** [dtretyakov/teamcity-azure-template#7]
The security center recommendations mandate installing an MMA on each VM.
![image](https://user-images.githubusercontent.com/4685167/57296878-b2bf0780-70eb-11e9-81ee-5930272a2157.png)

 After enabling the agent is inactive with "Agent not responsive or missing ID"
![image](https://user-images.githubusercontent.com/4685167/57296663-257bb300-70eb-11e9-98d3-789b8cd7c5bc.png)
Trying to manully install agent via steps at https://docs.microsoft.com/en-us/azure/azure-monitor/learn/quick-collect-azurevm or https://docs.microsoft.com/en-us/azure/azure-monitor/learn/quick-collect-linux-computer doesn't work since there is no rpm manager in CoreOS

![image](https://user-images.githubusercontent.com/4685167/57296760-670c5e00-70eb-11e9-9146-aac187fd6320.png)

How to we add monitoring and security on the teamcity VM?

**Comment by dtretyakov** [comment]
@anshulee, please ask questions regarding Azure monitoring agent in the following repository: https://github.com/microsoft/OMS-Agent-for-Linux/issues repository.

For CoreOS MSFT recommends using container monitoring agent: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/containers#install-and-configure-linux-container-hosts

In CoreOS you could [create a systemd service](https://coreos.com/os/docs/latest/getting-started-with-systemd.html) which will automatically execute required command on machine start.

**Comment by anshulee** [comment]
Thank you. Have added a query on the above mentioned repo too https://github.com/microsoft/OMS-Agent-for-Linux/issues/944

**Comment by anshulee** [comment]
Closing this issue as using the containerized agent worked for us . Thank you for the pointer
